<?php

namespace Database\Seeders;

use App\Models\Backend\RoleManagement\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        Permission::factory()
//            ->count(5)
//            ->create();

        Permission::insert([
            [
                'id' => 1,
                'permission_category_id'  => 1,
                'title'  => 'Super Admin Dashboard',
                'slug'  => 'super-admin-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 2,
                'permission_category_id'  => 1,
                'title'  => 'Admin Dashboard',
                'slug'  => 'admin-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 3,
                'permission_category_id'  => 1,
                'title'  => 'Teacher Dashboard',
                'slug'  => 'teacher-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 4,
                'permission_category_id'  => 1,
                'title'  => 'Student Dashboard',
                'slug'  => 'student-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 5,
                'permission_category_id'  => 1,
                'title'  => 'Stuff Dashboard',
                'slug'  => 'stuff-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 6,
                'permission_category_id'  => 1,
                'title'  => 'Normal User Dashboard',
                'slug'  => 'normal-user-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 7,
                'permission_category_id'  => 2,
                'title'  => 'Manage Permission Category',
                'slug'  => 'manage-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 8,
                'permission_category_id'  => 2,
                'title'  => 'Create Permission Category',
                'slug'  => 'create-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 9,
                'permission_category_id'  => 2,
                'title'  => 'Store Permission Category',
                'slug'  => 'store-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 10,
                'permission_category_id'  => 2,
                'title'  => 'Edit Permission Category ',
                'slug'  => 'edit-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 11,
                'permission_category_id'  => 2,
                'title'  => 'Update Permission Category',
                'slug'  => 'update-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 12,
                'permission_category_id'  => 2,
                'title'  => 'Show Permission Category',
                'slug'  => 'show-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 13,
                'permission_category_id'  => 2,
                'title'  => 'Delete Permission Category',
                'slug'  => 'delete-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],

            //      ================ Permission ===========
            [
                'id' => 14,
                'permission_category_id'  => 2,
                'title'         => 'Manage Permission',
                'slug'          => 'manage-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 15,
                'permission_category_id'  => 2,
                'title'         => 'Create Permission',
                'slug'          => 'create-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 16,
                'permission_category_id'  => 2,
                'title'         => 'Store Permission ',
                'slug'          => 'store-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 17,
                'permission_category_id'  => 2,
                'title'         => 'Edit Permission',
                'slug'          => 'edit-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 18,
                'permission_category_id'  => 2,
                'title'         => 'Update Permission',
                'slug'          => 'update-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 19,
                'permission_category_id'  => 2,
                'title'         => 'Show Permission',
                'slug'          => 'show-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 20,
                'permission_category_id'  => 2,
                'title'  => 'Delete Permission',
                'slug'  => 'delete-permission',
                'status'    => 1,
                'is_default'    => 1,
            ],

//      ================ Role ===========
            [
                'id' => 21,
                'permission_category_id'  => 3,
                'title'       => 'Manage Role',
                'slug'        => 'manage-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 22,
                'permission_category_id'  => 3,
                'title'      => 'Create Role',
                'slug'       => 'create-role',
                'status'     => 1,
                'is_default' => 1,
            ],
            [
                'id' => 23,
                'permission_category_id'  => 3,
                'title'         => 'Store Role ',
                'slug'          => 'store-role',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 24,
                'permission_category_id'  => 3,
                'title'         => 'Edit Role',
                'slug'          => 'edit-role',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 25,
                'permission_category_id'  => 3,
                'title'       => 'Update Role',
                'slug'        => 'update-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 26,
                'permission_category_id'  => 3,
                'title'       => 'Show Role',
                'slug'        => 'show-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 27,
                'permission_category_id'  => 3,
                'title'       => 'Delete Role',
                'slug'        => 'delete-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ User Role =================
            [
                'id' => 28,
                'permission_category_id'  => 3,
                'title'       => 'Manage User Role',
                'slug'        => 'manage-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 29,
                'permission_category_id'  => 3,
                'title'       => 'Create User Role',
                'slug'        => 'create-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 30,
                'permission_category_id'  => 3,
                'title'       => 'Store User Role ',
                'slug'        => 'store-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 31,
                'permission_category_id'  => 3,
                'title'       => 'Edit User Role',
                'slug'        => 'edit-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 32,
                'permission_category_id'  => 3,
                'title'       => 'Update User Role',
                'slug'        => 'update-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 33,
                'permission_category_id'  => 3,
                'title'       => 'Show User Role',
                'slug'        => 'show-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 34,
                'permission_category_id'  => 3,
                'title'       => 'Delete User Role',
                'slug'        => 'delete-user-role',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Course Category =================
            [
                'id' => 35,
                'permission_category_id'  => 4,
                'title'       => 'Manage Course Category',
                'slug'        => 'manage-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 36,
                'permission_category_id'  => 4,
                'title'       => 'Create Course Category',
                'slug'        => 'create-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 37,
                'permission_category_id'  => 4,
                'title'       => 'Store Course Category',
                'slug'        => 'store-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 38,
                'permission_category_id'  => 4,
                'title'       => 'Edit Course Category',
                'slug'        => 'edit-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 39,
                'permission_category_id'  => 4,
                'title'       => 'Update Course Category',
                'slug'        => 'update-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 40,
                'permission_category_id'  => 4,
                'title'       => 'Show Course Category',
                'slug'        => 'show-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 41,
                'permission_category_id'  => 4,
                'title'       => 'Delete Course Category',
                'slug'        => 'delete-course-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Course =================
            [
                'id' => 42,
                'permission_category_id'  => 4,
                'title'       => 'Manage Course',
                'slug'        => 'manage-course',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 43,
                'permission_category_id'  => 4,
                'title'       => 'Create Course',
                'slug'        => 'create-course',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 44,
                'permission_category_id'  => 4,
                'title'       => 'Store Course ',
                'slug'        => 'store-course',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 45,
                'permission_category_id'  => 4,
                'title'       => 'Edit Course',
                'slug'        => 'edit-course',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 46,
                'permission_category_id'  => 4,
                'title'       => 'Update Course',
                'slug'        => 'update-course',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 47,
                'permission_category_id'  => 4,
                'title'       => 'Show Course',
                'slug'        => 'show-course',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 48,
                'permission_category_id'  => 4,
                'title'       => 'Delete Course',
                'slug'        => 'delete-course',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Question =================
            [
                'id' => 49,
                'permission_category_id'  => 5,
                'title'       => 'Manage Question',
                'slug'        => 'manage-question',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 50,
                'permission_category_id'  => 5,
                'title'       => 'Create Question',
                'slug'        => 'create-question',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 51,
                'permission_category_id'  => 5,
                'title'       => 'Store Question',
                'slug'        => 'store-question',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 52,
                'permission_category_id'  => 5,
                'title'       => 'Edit Question',
                'slug'        => 'edit-question',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 53,
                'permission_category_id'  => 5,
                'title'       => 'Update Question',
                'slug'        => 'update-question',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 54,
                'permission_category_id'  => 5,
                'title'       => 'Show Question',
                'slug'        => 'show-question',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 55,
                'permission_category_id'  => 5,
                'title'       => 'Delete Question',
                'slug'        => 'delete-question',
                'status'      => 1,
                'is_default'  => 1,
            ],


// ================ Blog Category =================
            [
                'id' => 56,
                'permission_category_id'  => 6,
                'title'       => 'Manage Blog Category',
                'slug'        => 'manage-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 57,
                'permission_category_id'  => 6,
                'title'       => 'Create Blog Category',
                'slug'        => 'create-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 58,
                'permission_category_id'  => 6,
                'title'       => 'Store Blog Category',
                'slug'        => 'store-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 59,
                'permission_category_id'  => 6,
                'title'       => 'Edit Blog Category',
                'slug'        => 'edit-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 60,
                'permission_category_id'  => 6,
                'title'       => 'Update Blog Category',
                'slug'        => 'update-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 61,
                'permission_category_id'  => 6,
                'title'       => 'Show Blog Category',
                'slug'        => 'show-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 62,
                'permission_category_id'  => 6,
                'title'       => 'Delete Blog Category',
                'slug'        => 'delete-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Blog =================
            [
                'id' => 63,
                'permission_category_id'  => 6,
                'title'       => 'Manage Blog',
                'slug'        => 'manage-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 64,
                'permission_category_id'  => 6,
                'title'       => 'Create Blog',
                'slug'        => 'create-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 65,
                'permission_category_id'  => 6,
                'title'       => 'Store Blog',
                'slug'        => 'store-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 66,
                'permission_category_id'  => 6,
                'title'       => 'Edit Blog',
                'slug'        => 'edit-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 67,
                'permission_category_id'  => 6,
                'title'       => 'Update Blog',
                'slug'        => 'update-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 68,
                'permission_category_id'  => 6,
                'title'       => 'Show Blog',
                'slug'        => 'show-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 69,
                'permission_category_id'  => 6,
                'title'       => 'Delete Blog',
                'slug'        => 'delete-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Product Category =================
            [
                'id' => 70,
                'permission_category_id'  => 7,
                'title'       => 'Manage Product Category',
                'slug'        => 'manage-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 71,
                'permission_category_id'  => 7,
                'title'       => 'Create Product Category',
                'slug'        => 'create-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 72,
                'permission_category_id'  => 7,
                'title'       => 'Store Product Category',
                'slug'        => 'store-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 73,
                'permission_category_id'  => 7,
                'title'       => 'Edit Product Category',
                'slug'        => 'edit-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 74,
                'permission_category_id'  => 7,
                'title'       => 'Update Product Category',
                'slug'        => 'update-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 75,
                'permission_category_id'  => 7,
                'title'       => 'Show Product Category',
                'slug'        => 'show-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 76,
                'permission_category_id'  => 7,
                'title'       => 'Delete Product Category',
                'slug'        => 'delete-product-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================  Product Authors =================
            [
                'id' => 77,
                'permission_category_id'  => 7,
                'title'       => 'Manage Product Authors',
                'slug'        => 'manage-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 78,
                'permission_category_id'  => 7,
                'title'       => 'Create Product Authors',
                'slug'        => 'create-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 79,
                'permission_category_id'  => 7,
                'title'       => 'Store Product Authors',
                'slug'        => 'store-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 80,
                'permission_category_id'  => 7,
                'title'       => 'Edit Product Authors',
                'slug'        => 'edit-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 81,
                'permission_category_id'  => 7,
                'title'       => 'Update Product Authors',
                'slug'        => 'update-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 82,
                'permission_category_id'  => 7,
                'title'       => 'Show Product Authors',
                'slug'        => 'show-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 83,
                'permission_category_id'  => 7,
                'title'       => 'Delete Product Authors',
                'slug'        => 'delete-product-authors',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Product =================
            [
                'id' => 84,
                'permission_category_id'  => 7,
                'title'       => 'Manage Product',
                'slug'        => 'manage-product',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 85,
                'permission_category_id'  => 7,
                'title'       => 'Create Product',
                'slug'        => 'create-product',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 86,
                'permission_category_id'  => 7,
                'title'       => 'Store Product',
                'slug'        => 'store-product',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 87,
                'permission_category_id'  => 7,
                'title'       => 'Edit Product',
                'slug'        => 'edit-product',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 88,
                'permission_category_id'  => 7,
                'title'       => 'Update Product',
                'slug'        => 'update-product',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 89,
                'permission_category_id'  => 7,
                'title'       => 'Show Product',
                'slug'        => 'show-product',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 90,
                'permission_category_id'  => 7,
                'title'       => 'Delete Product',
                'slug'        => 'delete-product',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================  Job Circular Category =================
            [
                'id' => 91,
                'permission_category_id'  => 8,
                'title'       => 'Manage Job Circular Category',
                'slug'        => 'manage-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 92,
                'permission_category_id'  => 8,
                'title'       => 'Create Job Circular Category',
                'slug'        => 'create-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 93,
                'permission_category_id'  => 8,
                'title'       => 'Store Job Circular Category',
                'slug'        => 'store-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 94,
                'permission_category_id'  => 8,
                'title'       => 'Edit Job Circular Category',
                'slug'        => 'edit-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 95,
                'permission_category_id'  => 8,
                'title'       => 'Update Job Circular Category',
                'slug'        => 'update-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 96,
                'permission_category_id'  => 8,
                'title'       => 'Show Job Circular Category',
                'slug'        => 'show-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 97,
                'permission_category_id'  => 8,
                'title'       => 'Delete Job Circular Category',
                'slug'        => 'delete-job-circular-category',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================  Job Circular =================
            [
                'id' => 98,
                'permission_category_id'  => 8,
                'title'       => 'Manage Job Circular',
                'slug'        => 'manage-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 99,
                'permission_category_id'  => 8,
                'title'       => 'Create Job Circular',
                'slug'        => 'create-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 100,
                'permission_category_id'  => 8,
                'title'       => 'Store Job Circular',
                'slug'        => 'store-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 101,
                'permission_category_id'  => 8,
                'title'       => 'Edit Job Circular',
                'slug'        => 'edit-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 102,
                'permission_category_id'  => 8,
                'title'       => 'Update Job Circular',
                'slug'        => 'update-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 103,
                'permission_category_id'  => 8,
                'title'       => 'Show Job Circular',
                'slug'        => 'show-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 104,
                'permission_category_id'  => 8,
                'title'       => 'Delete Job Circular',
                'slug'        => 'delete-job-circular',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================  Notice Category =================
            [
                'id' => 105,
                'permission_category_id'  => 9,
                'title'       => 'Manage Notice Category',
                'slug'        => 'manage-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 106,
                'permission_category_id'  => 9,
                'title'       => 'Create Notice Category',
                'slug'        => 'create-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 107,
                'permission_category_id'  => 9,
                'title'       => 'Store Notice Category',
                'slug'        => 'store-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 108,
                'permission_category_id'  => 9,
                'title'       => 'Edit Notice Category',
                'slug'        => 'edit-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 109,
                'permission_category_id'  => 9,
                'title'       => 'Update Notice Category',
                'slug'        => 'update-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 110,
                'permission_category_id'  => 9,
                'title'       => 'Show Notice Category',
                'slug'        => 'show-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 111,
                'permission_category_id'  => 9,
                'title'       => 'Delete Notice Category',
                'slug'        => 'delete-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================  Notice =================
            [
                'id' => 112,
                'permission_category_id'  => 9,
                'title'       => 'Manage Notice',
                'slug'        => 'manage-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 113,
                'permission_category_id'  => 9,
                'title'       => 'Create Notice',
                'slug'        => 'create-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 114,
                'permission_category_id'  => 9,
                'title'       => 'Store Notice',
                'slug'        => 'store-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 115,
                'permission_category_id'  => 9,
                'title'       => 'Edit Notice',
                'slug'        => 'edit-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 116,
                'permission_category_id'  => 9,
                'title'       => 'Update Notice',
                'slug'        => 'update-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 117,
                'permission_category_id'  => 9,
                'title'       => 'Show Notice',
                'slug'        => 'show-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 118,
                'permission_category_id'  => 9,
                'title'       => 'Delete Notice',
                'slug'        => 'delete-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================  Model Test Category=================
            [
                'id' => 119,
                'permission_category_id'  => 10,
                'title'       => 'Manage Model Test Category',
                'slug'        => 'manage-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 120,
                'permission_category_id'  => 10,
                'title'       => 'Create Model Test Category',
                'slug'        => 'create-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 121,
                'permission_category_id'  => 10,
                'title'       => 'Store Model Test Category',
                'slug'        => 'store-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 122,
                'permission_category_id'  => 10,
                'title'       => 'Edit Model Test Category',
                'slug'        => 'edit-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 123,
                'permission_category_id'  => 10,
                'title'       => 'Update Model Test Category',
                'slug'        => 'update-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 124,
                'permission_category_id'  => 10,
                'title'       => 'Show Model Test Category',
                'slug'        => 'show-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 125,
                'permission_category_id'  => 10,
                'title'       => 'Delete Model Test Category',
                'slug'        => 'delete-model-test-category',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================  Model Test =================
            [
                'id' => 126,
                'permission_category_id'  => 10,
                'title'       => 'Manage Model Test',
                'slug'        => 'manage-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 127,
                'permission_category_id'  => 10,
                'title'       => 'Create Model Test',
                'slug'        => 'create-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 128,
                'permission_category_id'  => 10,
                'title'       => 'Store Model Test',
                'slug'        => 'store-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 129,
                'permission_category_id'  => 10,
                'title'       => 'Edit Model Test',
                'slug'        => 'edit-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 130,
                'permission_category_id'  => 10,
                'title'       => 'Update Model Test',
                'slug'        => 'update-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 131,
                'permission_category_id'  => 10,
                'title'       => 'Show Model Test',
                'slug'        => 'show-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 132,
                'permission_category_id'  => 10,
                'title'       => 'Delete Model Test',
                'slug'        => 'delete-model-test',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Order Delivery Options =================
            [
                'id' => 133,
                'permission_category_id'  => 11,
                'title'       => 'Manage Delivery Options',
                'slug'        => 'manage-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 134,
                'permission_category_id'  => 11,
                'title'       => 'Create Delivery Options',
                'slug'        => 'create-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 135,
                'permission_category_id'  => 11,
                'title'       => 'Store Delivery Options',
                'slug'        => 'store-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 136,
                'permission_category_id'  => 11,
                'title'       => 'Edit Delivery Options',
                'slug'        => 'edit-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 137,
                'permission_category_id'  => 11,
                'title'       => 'Update Delivery Options',
                'slug'        => 'update-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 138,
                'permission_category_id'  => 11,
                'title'       => 'Show Delivery Options',
                'slug'        => 'show-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 139,
                'permission_category_id'  => 11,
                'title'       => 'Delete Delivery Options',
                'slug'        => 'delete-delivery-options',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ All Order =================
            [
                'id' => 140,
                'permission_category_id'  => 11,
                'title'       => 'Manage Order',
                'slug'        => 'manage-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 141,
                'permission_category_id'  => 11,
                'title'       => 'Create Order',
                'slug'        => 'create-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 142,
                'permission_category_id'  => 11,
                'title'       => 'Store Order',
                'slug'        => 'store-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 143,
                'permission_category_id'  => 11,
                'title'       => 'Edit Order',
                'slug'        => 'edit-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 144,
                'permission_category_id'  => 11,
                'title'       => 'Update Order',
                'slug'        => 'update-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 145,
                'permission_category_id'  => 11,
                'title'       => 'Show Order',
                'slug'        => 'show-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 146,
                'permission_category_id'  => 11,
                'title'       => 'Delete Order',
                'slug'        => 'delete-order',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Course Order =================
            [
                'id' => 147,
                'permission_category_id'  => 11,
                'title'       => 'Manage Course Order',
                'slug'        => 'manage-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 148,
                'permission_category_id'  => 11,
                'title'       => 'Create Course Order',
                'slug'        => 'create-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 149,
                'permission_category_id'  => 11,
                'title'       => 'Store Course Order',
                'slug'        => 'store-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 150,
                'permission_category_id'  => 11,
                'title'       => 'Edit Course Order',
                'slug'        => 'edit-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 151,
                'permission_category_id'  => 11,
                'title'       => 'Update Course Order',
                'slug'        => 'update-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 152,
                'permission_category_id'  => 11,
                'title'       => 'Show Course Order',
                'slug'        => 'show-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 153,
                'permission_category_id'  => 11,
                'title'       => 'Delete Course Order',
                'slug'        => 'delete-course-order',
                'status'      => 1,
                'is_default'  => 1,
            ],


// ================ Product Order =================
            [
                'id' => 154,
                'permission_category_id'  => 11,
                'title'       => 'Manage Product Order',
                'slug'        => 'manage-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 155,
                'permission_category_id'  => 11,
                'title'       => 'Create Product Order',
                'slug'        => 'create-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 156,
                'permission_category_id'  => 11,
                'title'       => 'Store Product Order',
                'slug'        => 'store-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 157,
                'permission_category_id'  => 11,
                'title'       => 'Edit Product Order',
                'slug'        => 'edit-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 158,
                'permission_category_id'  => 11,
                'title'       => 'Update Product Order',
                'slug'        => 'update-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 159,
                'permission_category_id'  => 11,
                'title'       => 'Show Product Order',
                'slug'        => 'show-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 160,
                'permission_category_id'  => 11,
                'title'       => 'Delete Product Order',
                'slug'        => 'delete-product-order',
                'status'      => 1,
                'is_default'  => 1,
            ],


// ================ User =================
            [
                'id' => 161,
                'permission_category_id'  => 12,
                'title'       => 'Manage User',
                'slug'        => 'manage-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 162,
                'permission_category_id'  => 12,
                'title'       => 'Create User',
                'slug'        => 'create-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 163,
                'permission_category_id'  => 12,
                'title'       => 'Store User',
                'slug'        => 'store-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 164,
                'permission_category_id'  => 12,
                'title'       => 'Edit User',
                'slug'        => 'edit-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 165,
                'permission_category_id'  => 12,
                'title'       => 'Update User',
                'slug'        => 'update-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 166,
                'permission_category_id'  => 12,
                'title'       => 'Show User',
                'slug'        => 'show-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 167,
                'permission_category_id'  => 12,
                'title'       => 'Delete User',
                'slug'        => 'delete-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ User Profile=================
            [
                'id' => 168,
                'permission_category_id'  => 12,
                'title'       => 'Manage User Profile',
                'slug'        => 'manage-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 169,
                'permission_category_id'  => 12,
                'title'       => 'Create User Profile',
                'slug'        => 'create-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 170,
                'permission_category_id'  => 12,
                'title'       => 'Store User Profile',
                'slug'        => 'store-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 171,
                'permission_category_id'  => 12,
                'title'       => 'Edit User Profile',
                'slug'        => 'edit-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 172,
                'permission_category_id'  => 12,
                'title'       => 'Update User Profile',
                'slug'        => 'update-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 173,
                'permission_category_id'  => 12,
                'title'       => 'Show User Profile',
                'slug'        => 'show-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 174,
                'permission_category_id'  => 12,
                'title'       => 'Delete User Profile',
                'slug'        => 'delete-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],


// ================ Payment =================
            [
                'id' => 175,
                'permission_category_id'  => 13,
                'title'       => 'Manage Payment',
                'slug'        => 'manage-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 176,
                'permission_category_id'  => 13,
                'title'       => 'Create Payment',
                'slug'        => 'create-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 177,
                'permission_category_id'  => 13,
                'title'       => 'Store Payment',
                'slug'        => 'store-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 178,
                'permission_category_id'  => 13,
                'title'       => 'Edit Payment',
                'slug'        => 'edit-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 179,
                'permission_category_id'  => 13,
                'title'       => 'Update Payment',
                'slug'        => 'update-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 180,
                'permission_category_id'  => 13,
                'title'       => 'Show Payment',
                'slug'        => 'show-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 181,
                'permission_category_id'  => 13,
                'title'       => 'Delete Payment',
                'slug'        => 'delete-payment',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Page =================
            [
                'id' => 182,
                'permission_category_id'  => 14,
                'title'       => 'Manage Page',
                'slug'        => 'manage-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 183,
                'permission_category_id'  => 14,
                'title'       => 'Create Page',
                'slug'        => 'create-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 184,
                'permission_category_id'  => 14,
                'title'       => 'Store Page',
                'slug'        => 'store-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 185,
                'permission_category_id'  => 14,
                'title'       => 'Edit Page',
                'slug'        => 'edit-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 186,
                'permission_category_id'  => 14,
                'title'       => 'Update Page',
                'slug'        => 'update-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 187,
                'permission_category_id'  => 14,
                'title'       => 'Show Page',
                'slug'        => 'show-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 188,
                'permission_category_id'  => 14,
                'title'       => 'Delete Page',
                'slug'        => 'delete-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Contact =================
            [
                'id' => 189,
                'permission_category_id'  => 15,
                'title'       => 'Manage Contact',
                'slug'        => 'manage-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 190,
                'permission_category_id'  => 15,
                'title'       => 'Create Contact',
                'slug'        => 'create-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 191,
                'permission_category_id'  => 15,
                'title'       => 'Store Contact',
                'slug'        => 'store-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 192,
                'permission_category_id'  => 15,
                'title'       => 'Edit Contact',
                'slug'        => 'edit-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 193,
                'permission_category_id'  => 15,
                'title'       => 'Update Contact',
                'slug'        => 'update-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 194,
                'permission_category_id'  => 15,
                'title'       => 'Show Contact',
                'slug'        => 'show-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 195,
                'permission_category_id'  => 15,
                'title'       => 'Delete Contact',
                'slug'        => 'delete-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Advertisement =================
            [
                'id' => 196,
                'permission_category_id'  => 16,
                'title'       => 'Manage Advertisement',
                'slug'        => 'manage-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 197,
                'permission_category_id'  => 16,
                'title'       => 'Create Advertisement',
                'slug'        => 'create-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 198,
                'permission_category_id'  => 16,
                'title'       => 'Store Advertisement',
                'slug'        => 'store-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 199,
                'permission_category_id'  => 16,
                'title'       => 'Edit Advertisement',
                'slug'        => 'edit-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 200,
                'permission_category_id'  => 16,
                'title'       => 'Update Advertisement',
                'slug'        => 'update-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 201,
                'permission_category_id'  => 16,
                'title'       => 'Show Advertisement',
                'slug'        => 'show-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 202,
                'permission_category_id'  => 16,
                'title'       => 'Delete Advertisement',
                'slug'        => 'delete-advertisement',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Gallery =================
            [
                'id' => 203,
                'permission_category_id'  => 17,
                'title'       => 'Manage Gallery',
                'slug'        => 'manage-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 204,
                'permission_category_id'  => 17,
                'title'       => 'Create Gallery',
                'slug'        => 'create-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 205,
                'permission_category_id'  => 17,
                'title'       => 'Store Gallery',
                'slug'        => 'store-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 206,
                'permission_category_id'  => 17,
                'title'       => 'Edit Gallery',
                'slug'        => 'edit-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 207,
                'permission_category_id'  => 17,
                'title'       => 'Update Gallery',
                'slug'        => 'update-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 208,
                'permission_category_id'  => 17,
                'title'       => 'Show Gallery',
                'slug'        => 'show-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 209,
                'permission_category_id'  => 17,
                'title'       => 'Delete Gallery',
                'slug'        => 'delete-gallery',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Information =================
            [
                'id' => 210,
                'permission_category_id'  => 18,
                'title'       => 'Manage Information',
                'slug'        => 'manage-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 211,
                'permission_category_id'  => 18,
                'title'       => 'Create Information',
                'slug'        => 'create-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 212,
                'permission_category_id'  => 18,
                'title'       => 'Store Information',
                'slug'        => 'store-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 213,
                'permission_category_id'  => 18,
                'title'       => 'Edit Information',
                'slug'        => 'edit-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 214,
                'permission_category_id'  => 18,
                'title'       => 'Update Information',
                'slug'        => 'update-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 215,
                'permission_category_id'  => 18,
                'title'       => 'Show Information',
                'slug'        => 'show-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 216,
                'permission_category_id'  => 18,
                'title'       => 'Delete Information',
                'slug'        => 'delete-information',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Affiliation =================
            [
                'id' => 217,
                'permission_category_id'  => 19,
                'title'       => 'Manage Affiliation',
                'slug'        => 'manage-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 218,
                'permission_category_id'  => 19,
                'title'       => 'Create Affiliation',
                'slug'        => 'create-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 219,
                'permission_category_id'  => 19,
                'title'       => 'Store Affiliation',
                'slug'        => 'store-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 220,
                'permission_category_id'  => 19,
                'title'       => 'Edit Affiliation',
                'slug'        => 'edit-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 221,
                'permission_category_id'  => 19,
                'title'       => 'Update Affiliation',
                'slug'        => 'update-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 222,
                'permission_category_id'  => 19,
                'title'       => 'Show Affiliation',
                'slug'        => 'show-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 223,
                'permission_category_id'  => 19,
                'title'       => 'Delete Affiliation',
                'slug'        => 'delete-affiliation',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Notification =================
            [
                'id' => 224,
                'permission_category_id'  => 20,
                'title'       => 'Manage Notification',
                'slug'        => 'manage-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 225,
                'permission_category_id'  => 20,
                'title'       => 'Create Notification',
                'slug'        => 'create-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 226,
                'permission_category_id'  => 20,
                'title'       => 'Store Notification',
                'slug'        => 'store-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 227,
                'permission_category_id'  => 20,
                'title'       => 'Edit Notification',
                'slug'        => 'edit-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 228,
                'permission_category_id'  => 20,
                'title'       => 'Update Notification',
                'slug'        => 'update-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 229,
                'permission_category_id'  => 20,
                'title'       => 'Show Notification',
                'slug'        => 'show-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 230,
                'permission_category_id'  => 20,
                'title'       => 'Delete Notification',
                'slug'        => 'delete-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Enroll =================
            [
                'id' => 231,
                'permission_category_id'  => 21,
                'title'       => 'Manage Enroll',
                'slug'        => 'manage-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 232,
                'permission_category_id'  => 21,
                'title'       => 'Create Enroll',
                'slug'        => 'create-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 233,
                'permission_category_id'  => 21,
                'title'       => 'Store Enroll',
                'slug'        => 'store-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 234,
                'permission_category_id'  => 21,
                'title'       => 'Edit Enroll',
                'slug'        => 'edit-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 235,
                'permission_category_id'  => 21,
                'title'       => 'Update Enroll',
                'slug'        => 'update-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 236,
                'permission_category_id'  => 21,
                'title'       => 'Show Enroll',
                'slug'        => 'show-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 237,
                'permission_category_id'  => 21,
                'title'       => 'Delete Enroll',
                'slug'        => 'delete-enroll',
                'status'      => 1,
                'is_default'  => 1,
            ],
            // ================ Question Topics =================
            [
                'id' => 238,
                'permission_category_id'  => 5,
                'title'       => 'Manage Question Topics',
                'slug'        => 'manage-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 239,
                'permission_category_id'  => 5,
                'title'       => 'Create Question Topics',
                'slug'        => 'create-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 240,
                'permission_category_id'  => 5,
                'title'       => 'Store Question Topics',
                'slug'        => 'store-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 241,
                'permission_category_id'  => 5,
                'title'       => 'Edit Question Topics',
                'slug'        => 'edit-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 242,
                'permission_category_id'  => 5,
                'title'       => 'Update Question Topics',
                'slug'        => 'update-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 243,
                'permission_category_id'  => 5,
                'title'       => 'Show Question Topics',
                'slug'        => 'show-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 244,
                'permission_category_id'  => 5,
                'title'       => 'Delete Question Topics',
                'slug'        => 'delete-question-topics',
                'status'      => 1,
                'is_default'  => 1,
            ],
        ]);
    }
}
