<?php

namespace App\Models\Backend\BatchExamManagement;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class BatchExamSection extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'batch_exam_id',
        'title',
        'available_at',
        'note',
        'is_paid',
        'status',
        'order',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'batch_exam_sections';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($batchExamSection){
            if (!empty($batchExamSection->batchExamSectionContents))
            {
                $batchExamSection->batchExamSectionContents->each->delete();
            }
        });
    }

    protected static $batchExamSection;

    public static function createOrUpdateCourseSection ($request, $id = null)
    {
        if (isset($id))
        {
            self::$batchExamSection = BatchExamSection::find($id);
        } else {
            self::$batchExamSection = new BatchExamSection();
        }
        self::$batchExamSection->batch_exam_id      = $request->batch_exam_id;
        self::$batchExamSection->title              = $request->title;
        self::$batchExamSection->available_at       = $request->available_at;
        self::$batchExamSection->note               = $request->note;
        self::$batchExamSection->is_paid            = $request->is_paid == 'on' ? 1 : 0;
        self::$batchExamSection->status             = $request->status == 'on' ? 1 : 0;
        self::$batchExamSection->save();
    }

    public function batchExam()
    {
        return $this->belongsTo(BatchExam::class);
    }

    public function batchExamSectionContents()
    {
        return $this->hasMany(BatchExamSectionContent::class);
    }

    public function batchExamSectionContentsByAscOrder()
    {
        return $this->hasMany(BatchExamSectionContent::class)->orderBy('id', 'ASC');
    }
}
