<?php

namespace App\Models\Backend\Course;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CourseRoutine extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'course_id',
        'day',
        'date_time',
        'date_time_timestamp',
        'room',
        'note',
        'status',
        'is_fack',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'course_routines';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    protected static $courseRoutine;

    public static function createOrUpdateCourseRoutines ($request, $id = null)
    {
        CourseRoutine::updateOrCreate(['id' => $id], [
            'course_id'             => $request->course_id,
            'day'                   => $request->day,
            'date_time'             => $request->date_time,
            'date_time_timestamp'   => strtotime($request->date_time),
            'room'                  => $request->room,
            'note'                  => $request->note,
            'status'                => $request->status == 'on' ? 1 : 0,
            'is_fack'                => $request->is_fack == 'on' ? 1 : 0,
        ]);
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }
}
