<?php

namespace App\Models\Backend\Course;

use App\Models\Backend\QuestionManagement\QuestionStore;
use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CourseSectionContent extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'course_section_id',
        'parent_id',
        'content_type',
        'title',
        'pdf_link',
        'pdf_file',
        'note_content',
        'video_link',
        'video_vendor',
        'live_source_type',
        'live_link',
        'live_msg',
        'live_start_time',
        'live_start_time_timestamp',
        'live_end_time',
        'live_end_time_timestamp',
        'regular_link',
        'assignment_question',
        'assignment_instruction',
        'assignment_total_mark',
        'assignment_pass_mark',
        'assignment_start_time',
        'assignment_start_time_timestamp',
        'assignment_end_time',
        'assignment_end_time_timestamp',
        'assignment_result_publish_time',
        'assignment_result_publish_time_timestamp',
        'testmoj_link',
        'testmoj_result_link',
        'testmoj_xm_duration_in_minutes',
        'testmoj_total_questions',
        'testmoj_start_time',
        'testmoj_start_time_timestamp',
        'testmoj_result_publish_time',
        'testmoj_result_publish_time_timestamp',
        'exam_mode',
        'exam_duration_in_minutes',
        'exam_total_questions',
        'exam_per_question_mark',
        'exam_negative_mark',
        'exam_pass_mark',
        'exam_is_strict',
        'exam_start_time',
        'exam_start_time_timestamp',
        'exam_end_time',
        'exam_end_time_timestamp',
        'exam_result_publish_time',
        'exam_result_publish_time_timestamp',
        'exam_total_subject',
        'written_exam_duration_in_minutes',
        'written_total_questions',
        'written_description',
        'written_is_strict',
        'written_start_time',
        'written_start_time_timestamp',
        'written_end_time',
        'written_end_time_timestamp',
        'written_publish_time',
        'written_publish_time_timestamp',
        'written_total_subject',

        'is_paid',
        'order',
        'status',
        'available_at',
        'available_at_timestamp',

        'has_class_xm',
        'course_section_content_id',
        'class_xm_mark',
        'is_class_xm_complete',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'course_section_contents';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($sectionContent){
            if (file_exists($sectionContent->pdf_file))
            {
                unlink($sectionContent->pdf_file);
            }
            if (file_exists($sectionContent->pdf_file))
            {
                unlink($sectionContent->pdf_file);
            }
            if (file_exists($sectionContent->assignment_question))
            {
                unlink($sectionContent->assignment_question);
            }
            if (!empty($sectionContent->courseSectionContents))
            {
                $sectionContent->courseSectionContents->each->delete();
            }
        });
    }

    protected static $courseSectionContent;

    public static function saveOrUpdateCourseSectionContent ($request, $id = null)
    {
        if (isset($id))
        {
            self::$courseSectionContent                                             = CourseSectionContent::find($id);
        } else {
            self::$courseSectionContent                                             = new CourseSectionContent();
        }
        self::$courseSectionContent->course_section_id                              = $request->course_section_id;
        self::$courseSectionContent->parent_id                                      = $request->parent_id;
        self::$courseSectionContent->content_type                                   = $request->content_type;
        self::$courseSectionContent->title                                          = $request->title;
        self::$courseSectionContent->available_at                                   = $request->available_at;
        self::$courseSectionContent->available_at_timestamp                         = strtotime($request->available_at);

        self::$courseSectionContent->is_paid                                        = $request->is_paid == 'on' ? 1 : 0;
        self::$courseSectionContent->status                                         = $request->status == 'on' ? 1 : 0;
//        if ($request->has_class_xm == 'on')
//        {
            self::$courseSectionContent->has_class_xm                               = $request->has_class_xm == 'on' ? 1 : 0;
            self::$courseSectionContent->course_section_content_id                  = $request->has_class_xm == 'on' ? $request->course_section_content_id : null;
//        }
        if ($request->content_type == 'pdf')
        {
            self::$courseSectionContent->pdf_link                                   = $request->pdf_link;
            if ($request->pdf_select_form == 1)
            {
                self::$courseSectionContent->pdf_file                               = fileUpload($request->file('pdf_file'), 'course-section-content/pdf/', 'section-content', (isset($id) ? CourseSectionContent::find($id)->pdf_file : ''));
            } elseif (!empty($request->pdf_store_url) && $request->pdf_select_form == 2)
            {
                self::$courseSectionContent->pdf_file                               = $request->pdf_store_url;
            }
        } elseif ($request->content_type == 'video')
        {
            self::$courseSectionContent->video_vendor                               = $request->video_vendor;
            self::$courseSectionContent->video_link                                 = $request->video_link;
        } elseif ($request->content_type == 'note')
        {
            self::$courseSectionContent->note_content                               = $request->note_content;
        } elseif ($request->content_type == 'live')
        {
            self::$courseSectionContent->live_source_type                           = $request->live_source_type;
            self::$courseSectionContent->live_link                                  = $request->live_link;
            self::$courseSectionContent->live_msg                                   = $request->live_msg;
            self::$courseSectionContent->live_start_time                            = $request->live_start_time;
            self::$courseSectionContent->live_start_time_timestamp                  = strtotime($request->live_start_time);
            self::$courseSectionContent->live_end_time                              = $request->live_end_time;
            self::$courseSectionContent->live_end_time_timestamp                    = strtotime($request->live_end_time);
        } elseif ($request->content_type == 'link')
        {
            self::$courseSectionContent->regular_link                               = $request->regular_link;
        } elseif ($request->content_type == 'assignment')
        {
            self::$courseSectionContent->assignment_question                        = fileUpload($request->file('assignment_question'),'course-section-content/assignment/', 'assignment', (isset($id) ? CourseSectionContent::find($id)->assignment_question : ''));
            self::$courseSectionContent->assignment_instruction                     = $request->assignment_instruction;
            self::$courseSectionContent->assignment_total_mark                      = $request->assignment_total_mark;
            self::$courseSectionContent->assignment_pass_mark                       = $request->assignment_pass_mark;
            self::$courseSectionContent->assignment_start_time                      = $request->assignment_start_time;
            self::$courseSectionContent->assignment_start_time_timestamp            = strtotime($request->assignment_start_time);
            self::$courseSectionContent->assignment_end_time                        = $request->assignment_end_time;
            self::$courseSectionContent->assignment_end_time_timestamp              = strtotime($request->assignment_end_time);
            self::$courseSectionContent->assignment_result_publish_time             = $request->assignment_result_publish_time;
            self::$courseSectionContent->assignment_result_publish_time_timestamp   = strtotime($request->assignment_result_publish_time);
        } elseif ($request->content_type == 'testmoj')
        {
            self::$courseSectionContent->testmoj_link                               = $request->testmoj_link;
            self::$courseSectionContent->testmoj_result_link                        = $request->testmoj_result_link;
            self::$courseSectionContent->testmoj_xm_duration_in_minutes             = $request->testmoj_xm_duration_in_minutes;
            self::$courseSectionContent->testmoj_total_questions                    = $request->testmoj_total_questions;
            self::$courseSectionContent->testmoj_start_time                         = $request->testmoj_start_time;
            self::$courseSectionContent->testmoj_start_time_timestamp               = strtotime($request->testmoj_start_time);
            self::$courseSectionContent->testmoj_result_publish_time                = $request->testmoj_result_publish_time;
            self::$courseSectionContent->testmoj_result_publish_time_timestamp      = strtotime($request->testmoj_result_publish_time);
        } elseif ($request->content_type == 'exam')
        {
            self::$courseSectionContent->exam_mode  = $request->exam_mode;

            self::$courseSectionContent->exam_duration_in_minutes                   = $request->exam_duration_in_minutes;
            self::$courseSectionContent->exam_total_questions                       = $request->exam_total_questions;
            self::$courseSectionContent->exam_per_question_mark                     = $request->exam_per_question_mark;
            self::$courseSectionContent->exam_negative_mark                         = $request->exam_negative_mark;
            self::$courseSectionContent->exam_pass_mark                             = $request->exam_pass_mark;

            if ((self::$courseSectionContent->exam_mode == 'exam') || (self::$courseSectionContent->exam_mode == 'group') )
            {
                self::$courseSectionContent->exam_is_strict                         = $request->exam_is_strict == 'on' ? 1 : 0;
                self::$courseSectionContent->exam_start_time                        = $request->exam_start_time;
                self::$courseSectionContent->exam_start_time_timestamp              = strtotime($request->exam_start_time);
                self::$courseSectionContent->exam_end_time                          = $request->exam_end_time;
                self::$courseSectionContent->exam_end_time_timestamp                = strtotime($request->exam_end_time);
                self::$courseSectionContent->exam_result_publish_time               = $request->exam_result_publish_time;
                self::$courseSectionContent->exam_result_publish_time_timestamp     = strtotime($request->exam_result_publish_time);
            }
            if (self::$courseSectionContent->exam_mode == 'group')
            {
                self::$courseSectionContent->exam_total_subject                     = $request->exam_total_subject;
            }
        } elseif ($request->content_type == 'written_exam')
        {
            self::$courseSectionContent->written_exam_duration_in_minutes           = $request->written_exam_duration_in_minutes;
            self::$courseSectionContent->written_total_questions                    = $request->written_total_questions;
            self::$courseSectionContent->written_description                        = $request->written_description;
            self::$courseSectionContent->written_is_strict                          = $request->written_is_strict == 'on' ? 1 : 0;
            self::$courseSectionContent->written_start_time                         = $request->written_start_time;
            self::$courseSectionContent->written_start_time_timestamp               = strtotime($request->written_start_time);
            self::$courseSectionContent->written_end_time                           = $request->written_end_time;
            self::$courseSectionContent->written_end_time_timestamp                 = strtotime($request->written_end_time);
            self::$courseSectionContent->written_publish_time                       = $request->written_publish_time;
            self::$courseSectionContent->written_publish_time_timestamp             = strtotime($request->written_publish_time);
            self::$courseSectionContent->written_total_subject                      = $request->written_total_subject;
        }
        self::$courseSectionContent->save();
    }

    public function courseSection()
    {
        return $this->belongsTo(CourseSection::class);
    }

    public function courseSectionContent()
    {
        return $this->belongsTo(CourseSectionContent::class, 'parent_id');
    }

    public function courseSectionContents()
    {
        return $this->hasMany(CourseSectionContent::class, 'parent_id');
    }
    public function questionStores()
    {
        return $this->belongsToMany(QuestionStore::class);
    }

    public function courseExamResults()
    {
        return $this->hasMany(CourseExamResult::class);
    }

    public function courseSectionContentClassXm()
    {
        return $this->belongsTo(
            CourseSectionContent::class,
            'course_section_content_id'
        );
    }

    public function courseSectionContentsSub()
    {
        return $this->hasMany(
            CourseSectionContent::class,
            'course_section_content_id'
        );
    }

    public function questionStoresForClassXm()
    {
        return $this->belongsToMany(
            QuestionStore::class,
            'course_section_content_question_store_class'
        );
    }
}
