<?php

namespace App\Models\Backend\Course;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CourseSection extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'course_id',
        'title',
        'available_at',
        'note',
        'is_paid',
        'status',
        'order',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'course_sections';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($courseSection){
            if (!empty($courseSection->courseSectionContents))
            {
                $courseSection->courseSectionContents->each->delete();
            }
        });
    }

    protected static $courseSection;

    public static function createOrUpdateCourseSection ($request, $id = null)
    {
        if (isset($id))
        {
            self::$courseSection = CourseSection::find($id);
        } else {
            self::$courseSection = new CourseSection();
        }
        self::$courseSection->course_id = $request->course_id;
        self::$courseSection->title = $request->title;
        self::$courseSection->available_at = $request->available_at;
        self::$courseSection->note = $request->note;
        self::$courseSection->is_paid = $request->is_paid == 'on' ? 1 : 0;
        self::$courseSection->status = $request->status == 'on' ? 1 : 0;
        self::$courseSection->save();
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function courseSectionContents()
    {
        return $this->hasMany(CourseSectionContent::class);
    }
}
